name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Goodbye Universe action step
        uses: ./ # Uses an action in the root directory
